// <auto-generated />
namespace PSX.Services;

public static class BridgeProtocolLimits
{
    public const int AgentWireEnvelopeCharacters = 75497472;
    public const int TerminalWireEnvelopeCharacters = 75497472;
    public const int AgentPromptTextCharacters = 1048576;
    public const int TerminalInputBytes = 4194304;
    public const int ImageBytes = 20971520;
    public const int PromptImageBytes = 52428800;
    public const int PromptImageCount = 5;
    public const int AvatarBytes = 524288;
}
