<#
.SYNOPSIS
    Build a redistributable PSX release zip.

.DESCRIPTION
    Produces PSX-{version}-win-x64-portable.zip containing:
      - PSX.exe, PSX.dll and all self-contained .NET runtime files (win-x64)
      - wwwroot/, psx.ini, theme-presets/   (copied from publish output)
      - tools/node/                          (portable Node 22.23.1, downloaded)
      - tools/acp-seed/                      (installed by the user on first Agent use)
      - tools/dsh-seed/                      (installed by the user on first DSH use)
      - tools/dsh-locks/                     (hash-pinned pre-generated DSH update
                                              locks; verified statically here,
                                              generated by generate-dsh-lock.ps1
                                              in its disposable environment)
      - tools/kimi/                          (Kimi Code ACP runtime, installed at
                                              build time at the latest published version, or from tools/kimi-seed/ via npm ci)
      - tools/qwen/                          (Qwen Code ACP runtime, installed at
                                              build time at the latest published version, or from tools/qwen-seed/ via npm ci)
      - tools/opencode/                      (OpenCode ACP runtime - native
                                              Bun-compiled binary, installed at
                                              build time at the latest published version, or from tools/opencode-seed/
                                              via npm ci)

    The output zip is portable for end users: unzip and double-click PSX.exe.
    .NET and Node are bundled. Agent mode asks for confirmation before it
    downloads the Claude managed runtime from npm on first use.
    WebView2 Runtime can be bundled by passing -WebView2FixedRuntimePath.
    Otherwise machines without it will see a prompt asking the user to install
    it manually.

    This script does NOT install Node on the build machine. The
    portable Node is downloaded as a .zip archive and extracted with
    PowerShell's built-in Expand-Archive (no third-party tools required).

.PARAMETER Configuration
    Build configuration. Release by default.

.PARAMETER OutputDirectory
    Where the final zip lands. Defaults to .\bin\releases under the repository.

.PARAMETER SkipNodeDownload
    If set, network download is disabled and the already-cached Node archive
    must exist under bin/build-cache. The cached archive is still verified and
    extracted into the package.

.PARAMETER StagingDirectory
    Optional fresh staging directory beneath bin/ or TestResults/. Use this
    when a running development build still owns the default release-staging
    directory. An explicit staging directory must not already exist.

.PARAMETER WebView2FixedRuntimePath
    Optional path to an extracted WebView2 Fixed Version Runtime directory.
    The directory must contain msedgewebview2.exe, either directly or in a
    nested Microsoft.WebView2.FixedVersionRuntime.* folder. When provided, the
    runtime is copied into runtime/webview2-fixed/ in the release package.

.PARAMETER SkipOpenCodeSmoke
    If set, the OpenCode native smokes (opencode.exe --version and the ACP
    initialize probe) are not executed. Use only on build machines where
    security software (Defender/EDR/360) blocks the unsigned Bun-compiled
    binary from running. The script then verifies the bundled binary
    statically: the platform package's package.json version must match the
    seed manifest pin. The produced package MUST be smoke-tested on a machine
    where opencode.exe is allowed to run.

.PARAMETER SkipDshFreshnessCheck
    Compatibility switch. DSH freshness is no longer checked by default.
    Cannot be combined with RequireLatestDsh.

.PARAMETER RequireLatestDsh
    Opt-in metadata audit: the highest published DSH version above the seed
    must be catalogued or explicitly blocked. This does NOT require the seed
    itself to be the latest version. Registry query failures are fatal.

.PARAMETER PinRuntimes
    If set, Kimi/Qwen/OpenCode are installed reproducibly from their committed
    tools/*-seed/package-lock.json via `npm ci`. By default the release resolves
    each package's official npm `latest` dist-tag at build time and installs that
    exact version, so a build always ships the newest stable runtimes; every
    bundle is still smoke-checked before packaging. This trades build
    reproducibility for currency. DSH is unaffected and always installs from the
    hash-pinned seed and catalog.

.EXAMPLE
    pwsh tools/build-release.ps1
    pwsh tools/build-release.ps1 -Configuration Debug -OutputDirectory .\out\
#>

[CmdletBinding()]
param(
    [string]$Configuration = "Release",
    [string]$OutputDirectory = "",
    [string]$StagingDirectory = "",
    [switch]$SkipNodeDownload,
    [string]$WebView2FixedRuntimePath = "",
    [switch]$SkipOpenCodeSmoke,
    [switch]$SkipDshFreshnessCheck,
    [switch]$RequireLatestDsh,
    [switch]$PinRuntimes
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"
Set-StrictMode -Version Latest
if ($RequireLatestDsh -and $SkipDshFreshnessCheck) {
    throw "RequireLatestDsh and SkipDshFreshnessCheck cannot be combined."
}
if ($SkipDshFreshnessCheck) {
    Write-Warning "SkipDshFreshnessCheck is obsolete: DSH freshness is not checked by default."
}

# ---- pin everything for reproducible builds ----
function Assert-DshSeedConsistency {
    param([string]$SeedRoot, [string]$LocksRoot, [object[]]$Entries,
        [string]$PinnedVersion, [string]$RuntimeSource)
    $matching = @($Entries | Where-Object { $_.version -ceq $PinnedVersion })
    if ($matching.Count -ne 1) { throw 'DSH seed must have exactly one catalog entry.' }
    $artifactRoot = Join-Path $LocksRoot ("locks\" + $PinnedVersion)
    foreach ($name in @('package.json', 'package-lock.json')) {
        $seedBytes = [IO.File]::ReadAllBytes((Join-Path $SeedRoot $name))
        $artifactBytes = [IO.File]::ReadAllBytes((Join-Path $artifactRoot $name))
        if ([Convert]::ToBase64String($seedBytes) -cne [Convert]::ToBase64String($artifactBytes)) {
            throw "DSH seed $name differs from its catalog artifact."
        }
    }
    $declarations = [regex]::Matches($RuntimeSource, 'public const string SeededPackageVersion = "([^"]+)";')
    if ($declarations.Count -ne 1 -or $declarations[0].Groups[1].Value -cne $PinnedVersion) {
        throw 'DSH runtime seed declaration differs from the release seed.'
    }
}

$PortableNodeVersion = "v22.23.1"
$PortableNodeArchive = "node-$PortableNodeVersion-win-x64.zip"
$PortableNodeUrl = "https://nodejs.org/dist/$PortableNodeVersion/$PortableNodeArchive"
$PortableNodeExpectedSha = "7df0bc9375723f4a86b3aa1b7cc73342423d9677a8df4538aca31a049e309c29"
$MapleMonoRegularExpectedSha = "E42D081EAECBDA6A043079EAAAF43EA20BD8805666BC06E1FE4DC663C462AD7F"
$MapleMonoSemiBoldExpectedSha = "F72D4475C7AC435C7C363E0CB35100A18E4A5BB14787F17F7BBC64823B904066"
$DshSeedLockExpectedSha = "A2E6AC98CDFF90945C7558E2A1A8FFA03346EB9B8AF431B36188BE385CCC525E"
$DshPinnedVersion = "0.1.5-rc.2"
# SHA-256 of tools/dsh-locks/catalog.json. Update it (and review the diff)
# whenever the DSH lock catalog changes; the release machine never executes
# new package code, this pin is its only catalog trust evidence.
$DshLockCatalogExpectedSha = "A68F2E6D346275252D4131D29C9A5B6F380896394670CF516B4908A6CFF3421A"
$DshLockBlockedReasons = @("smoke_failed", "official_integrity_mismatch", "sri_conflict")

# ---- locate repo root ----
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Resolve-Path (Join-Path $ScriptDir "..")).Path
$ProjectPath = Join-Path $RepoRoot "PSX.csproj"
$PublishOutput = [IO.Path]::GetFullPath((Join-Path $RepoRoot "bin\publish\win-x64-self-contained"))
$StagingDir = [IO.Path]::GetFullPath((Join-Path $RepoRoot "bin\release-staging"))
if (-not [string]::IsNullOrWhiteSpace($StagingDirectory)) {
    $StagingDir = if ([IO.Path]::IsPathRooted($StagingDirectory)) {
        [IO.Path]::GetFullPath($StagingDirectory)
    } else {
        [IO.Path]::GetFullPath((Join-Path $RepoRoot $StagingDirectory))
    }
    $allowedStagingRoots = @("bin", "TestResults") | ForEach-Object {
        [IO.Path]::GetFullPath((Join-Path $RepoRoot $_)) + [IO.Path]::DirectorySeparatorChar
    }
    if (-not ($allowedStagingRoots | Where-Object { $StagingDir.StartsWith($_, [StringComparison]::OrdinalIgnoreCase) })) {
        throw "Explicit staging directory must be beneath repository bin/ or TestResults/."
    }
    if (Test-Path -LiteralPath $StagingDir) {
        throw "Explicit staging directory must be fresh; choose a new directory instead of removing an in-use build."
    }
}
$BuildCacheDir = [IO.Path]::GetFullPath((Join-Path $RepoRoot "bin\build-cache"))
if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $OutputDirectory = [IO.Path]::GetFullPath((Join-Path $RepoRoot "bin\releases"))
} elseif (-not [IO.Path]::IsPathRooted($OutputDirectory)) {
    $OutputDirectory = [IO.Path]::GetFullPath((Join-Path $RepoRoot $OutputDirectory))
} else {
    $OutputDirectory = [IO.Path]::GetFullPath($OutputDirectory)
}

function Resolve-WebView2FixedRuntimeDirectory {
    param([string]$Path)

    if ([string]::IsNullOrWhiteSpace($Path)) {
        return $null
    }

    $resolved = Resolve-Path $Path -ErrorAction Stop
    $item = Get-Item $resolved
    if (-not $item.PSIsContainer) {
        throw "WebView2FixedRuntimePath must be an extracted directory, not a file: $Path"
    }

    $directExe = Join-Path $item.FullName "msedgewebview2.exe"
    if (Test-Path $directExe) {
        return $item.FullName
    }

    $runtimeExe = Get-ChildItem -Path $item.FullName -Filter "msedgewebview2.exe" -Recurse -File |
        Select-Object -First 1
    if ($null -eq $runtimeExe) {
        throw "msedgewebview2.exe was not found under WebView2FixedRuntimePath: $Path"
    }

    return $runtimeExe.DirectoryName
}

Write-Host "==> PSX release build" -ForegroundColor Cyan
Write-Host "    Repo root:        $RepoRoot"
Write-Host "    Configuration:   $Configuration"
Write-Host "    Publish output:  $PublishOutput"
Write-Host "    Staging dir:     $StagingDir"
Write-Host "    Output dir:      $OutputDirectory"
if (-not [string]::IsNullOrWhiteSpace($WebView2FixedRuntimePath)) {
    Write-Host "    WebView2 fixed:  $WebView2FixedRuntimePath"
}
Write-Host ""

# ---- step 1: dotnet publish ----
Write-Host "==> [1/7] dotnet publish (self-contained, win-x64, non-single-file)" -ForegroundColor Cyan
if (Test-Path $PublishOutput) {
    Remove-Item -Recurse -Force $PublishOutput
}
$publishProfile = Join-Path $RepoRoot "Properties\PublishProfiles\win-x64-self-contained.pubxml"
if (-not (Test-Path $publishProfile)) {
    throw "Publish profile not found: $publishProfile. Did you forget to add it?"
}
dotnet publish $ProjectPath `
    -c $Configuration `
    /p:PublishProfile=win-x64-self-contained `
    -o $PublishOutput | Out-Host
if ($LASTEXITCODE -ne 0) { throw "dotnet publish failed (exit $LASTEXITCODE)" }
Write-Host ""

# ---- step 2: stage publish output ----
Write-Host "==> [2/7] Stage publish output" -ForegroundColor Cyan
if (Test-Path $StagingDir) {
    Remove-Item -Recurse -Force $StagingDir
}
New-Item -ItemType Directory -Path $StagingDir | Out-Null
Copy-Item -Recurse -Force (Join-Path $PublishOutput "*") $StagingDir
Write-Host "    Staged $((Get-ChildItem -Recurse $StagingDir | Measure-Object).Count) files"
Write-Host ""

# ---- step 3: portable Node ----
$nodeDir = Join-Path $StagingDir "tools\node"
$archivePath = Join-Path $BuildCacheDir $PortableNodeArchive
New-Item -ItemType Directory -Path $BuildCacheDir -Force | Out-Null
if ($SkipNodeDownload) {
    Write-Host "==> [3/7] Use cached portable Node $PortableNodeVersion" -ForegroundColor Cyan
    if (-not (Test-Path $archivePath)) {
        throw "-SkipNodeDownload requires the verified archive at: $archivePath"
    }
} else {
    Write-Host "==> [3/7] Download + extract portable Node $PortableNodeVersion" -ForegroundColor Cyan
    if (-not (Test-Path $archivePath)) {
        Write-Host "    Downloading $PortableNodeUrl"
        Invoke-WebRequest -Uri $PortableNodeUrl -OutFile $archivePath -UseBasicParsing
    } else {
        Write-Host "    Reusing cached archive: $archivePath"
    }
}

$actualSha = (Get-FileHash -LiteralPath $archivePath -Algorithm SHA256).Hash
if (-not [string]::Equals($actualSha, $PortableNodeExpectedSha, [StringComparison]::OrdinalIgnoreCase)) {
    Remove-Item -LiteralPath $archivePath -Force
    throw "Portable Node SHA-256 mismatch. Expected $PortableNodeExpectedSha but got $actualSha. The cached archive was deleted."
}
Write-Host "    Verified SHA-256: $actualSha"

New-Item -ItemType Directory -Path $nodeDir -Force | Out-Null
Write-Host "    Extracting zip to $nodeDir"
Expand-Archive -Path $archivePath -DestinationPath $nodeDir -Force

# zip extracts to node-vXX.YY.Z-win-x64/ — flatten to tools/node/ directly
$extractedRoot = Get-ChildItem -Directory $nodeDir | Select-Object -First 1
if ($extractedRoot) {
    Get-ChildItem $extractedRoot.FullName -Force | Move-Item -Destination $nodeDir -Force
    Remove-Item -Recurse -Force $extractedRoot.FullName
}

Set-Content -Path (Join-Path $nodeDir "node-version.txt") -Value $PortableNodeVersion -NoNewline
Write-Host "    Installed Node into staging/tools/node/; wrote node-version.txt"
Write-Host ""

# ---- mandatory zstd smoke for the DSH usage extractor on the pinned Node ----
# The extractor relies on per-frame zstdDecompressSync (node:zlib streaming
# drops concatenated frames); this gate proves the pinned Node decodes a
# synthetic multi-frame session log and flags a truncated tail frame. Failure
# must block the release (acceptance: never validated on a dev-machine Node).
$dshExtractor = Join-Path $StagingDir "tools\usage-extractor\dsh-session-extract.mjs"
if (-not (Test-Path -LiteralPath $dshExtractor -PathType Leaf)) {
    throw "DSH usage extractor missing from staging: tools/usage-extractor/dsh-session-extract.mjs"
}
$zstdSmokeDir = Join-Path $StagingDir "tmp-zstd-smoke"
New-Item -ItemType Directory -Path $zstdSmokeDir -Force | Out-Null
$zstdFixture = Join-Path $zstdSmokeDir "session.jsonl.zstd"
$zstdTruncatedFixture = Join-Path $zstdSmokeDir "session-truncated.jsonl.zstd"
$nodeExe = Join-Path $nodeDir "node.exe"
$zstdFixtureScript = Join-Path $StagingDir "tools\usage-extractor\zstd-smoke-fixture.mjs"
if (-not (Test-Path -LiteralPath $zstdFixtureScript -PathType Leaf)) {
    throw "DSH zstd smoke fixture generator missing from staging: tools/usage-extractor/zstd-smoke-fixture.mjs"
}
& $nodeExe $zstdFixtureScript $zstdFixture $zstdTruncatedFixture
if ($LASTEXITCODE -ne 0) { throw "zstd smoke fixture generation failed (exit $LASTEXITCODE)" }
$zstdSmokeOut = ("$zstdFixture" | & $nodeExe $dshExtractor 2>&1 | Out-String)
if ($LASTEXITCODE -ne 0) { throw "DSH extractor zstd smoke failed on pinned Node (exit $LASTEXITCODE): $zstdSmokeOut" }
foreach ($expected in @('"k":"usage"', '"in":3', '"out":4', '"cr":5', '"cw":6', '"frames":2', '"truncated":false')) {
    if (-not $zstdSmokeOut.Contains($expected)) { throw "DSH extractor zstd smoke missing $expected. Output: $zstdSmokeOut" }
}
$zstdTruncOut = ("$zstdTruncatedFixture" | & $nodeExe $dshExtractor 2>&1 | Out-String)
if ($LASTEXITCODE -ne 0) { throw "DSH extractor truncated-tail smoke failed (exit $LASTEXITCODE): $zstdTruncOut" }
if (-not $zstdTruncOut.Contains('"truncated":true')) { throw "DSH extractor did not flag the truncated tail frame. Output: $zstdTruncOut" }
Remove-Item -Recurse -Force $zstdSmokeDir
Write-Host "    DSH usage extractor zstd smoke passed on pinned Node $PortableNodeVersion"
Write-Host ""

# ---- runtime bundle installer ----
# Default (always-current): resolve each runtime package's official npm `latest`
# dist-tag at build time and install that exact version, so a release always
# ships the newest stable Kimi/Qwen/OpenCode. -PinRuntimes restores the previous
# reproducible behavior (`npm ci` from the committed seed lockfile). Either way
# the seed .npmrc keeps os/cpu pinned to win32-x64 and the registry official, and
# --include=optional pulls the win32-x64 native components (node-pty,
# clipboard-win32-x64, opencode-windows-x64). Each bundle is smoke-checked below.
function Install-BundledRuntime {
    param(
        [string]$Label,
        [string]$PackageName,
        [string]$SeedDir,
        [string]$TargetDir,
        [string]$NodeExe,
        [string]$NpmCli
    )
    foreach ($seedFile in @("package.json", ".npmrc")) {
        if (-not (Test-Path -LiteralPath (Join-Path $SeedDir $seedFile) -PathType Leaf)) {
            throw "$Label seed file is missing: $SeedDir\$seedFile"
        }
    }
    New-Item -ItemType Directory -Path $TargetDir -Force | Out-Null
    Copy-Item (Join-Path $SeedDir "package.json") $TargetDir -Force
    Copy-Item (Join-Path $SeedDir ".npmrc") $TargetDir -Force

    if ($PinRuntimes) {
        $seedLock = Join-Path $SeedDir "package-lock.json"
        if (-not (Test-Path -LiteralPath $seedLock -PathType Leaf)) {
            throw "$Label seed lockfile is missing (required by -PinRuntimes): $seedLock"
        }
        Copy-Item $seedLock $TargetDir -Force
        & $NodeExe $NpmCli ci --prefix $TargetDir --omit=dev --include=optional --no-audit --no-fund | Out-Host
        if ($LASTEXITCODE -ne 0) { throw "npm ci for $Label failed (exit $LASTEXITCODE)" }
        Write-Host "    Installed $Label from the pinned seed lockfile (-PinRuntimes)."
        return $null
    }

    $resolved = (& $NodeExe $NpmCli view $PackageName version --registry=https://registry.npmjs.org/ | Out-String).Trim()
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($resolved)) {
        throw "Could not resolve the latest $PackageName version from the official registry (npm view exit $LASTEXITCODE): $resolved"
    }
    if ($resolved -notmatch '^\d+\.\d+\.\d+$') {
        throw "Resolved latest $PackageName version '$resolved' is not a clean X.Y.Z release; refusing to auto-bundle a prerelease."
    }
    Write-Host "    Resolved latest $PackageName -> $resolved (official npm 'latest' tag)"
    & $NodeExe $NpmCli install "$PackageName@$resolved" --prefix $TargetDir --save-exact --omit=dev --include=optional --no-audit --no-fund | Out-Host
    if ($LASTEXITCODE -ne 0) { throw "npm install for $Label ($PackageName@$resolved) failed (exit $LASTEXITCODE)" }
    return $resolved
}

$nodeExe = Join-Path $nodeDir "node.exe"
$npmCli = Join-Path $nodeDir "node_modules\npm\bin\npm-cli.js"

# ---- step 4: bundle Kimi Code ACP runtime ----
Write-Host "==> [4/7] Install Kimi Code ACP runtime into staging/tools/kimi" -ForegroundColor Cyan
$kimiSeedDir = Join-Path $RepoRoot "tools\kimi-seed"
$kimiTargetDir = Join-Path $StagingDir "tools\kimi"
Install-BundledRuntime -Label "Kimi Code" -PackageName "@moonshot-ai/kimi-code" -SeedDir $kimiSeedDir -TargetDir $kimiTargetDir -NodeExe $nodeExe -NpmCli $npmCli | Out-Null

# Smoke-check the bundled entry actually starts on the portable Node instead
# of only checking the file exists. Capture output first (no Out-Host pipe:
# empty output must be detectable), then check the exit code and emptiness.
$kimiEntry = Join-Path $kimiTargetDir "node_modules\@moonshot-ai\kimi-code\dist\main.mjs"
if (-not (Test-Path -LiteralPath $kimiEntry -PathType Leaf)) {
    throw "Bundled Kimi entry is missing: $kimiEntry"
}
$kimiSmokeOutput = (& $nodeExe $kimiEntry --version 2>&1 | Out-String).Trim()
if ($LASTEXITCODE -ne 0) { throw "Bundled Kimi smoke check failed (exit $LASTEXITCODE): $kimiSmokeOutput" }
if ([string]::IsNullOrWhiteSpace($kimiSmokeOutput)) { throw "Bundled Kimi smoke check produced no output" }
Write-Host "    Kimi smoke check passed: --version -> $kimiSmokeOutput"
Write-Host "    Installed Kimi Code into staging/tools/kimi/"
Write-Host ""

# ---- step 5: bundle Qwen Code ACP runtime ----
Write-Host "==> [5/7] Install Qwen Code ACP runtime into staging/tools/qwen" -ForegroundColor Cyan
$qwenSeedDir = Join-Path $RepoRoot "tools\qwen-seed"
$qwenTargetDir = Join-Path $StagingDir "tools\qwen"
Install-BundledRuntime -Label "Qwen Code" -PackageName "@qwen-code/qwen-code" -SeedDir $qwenSeedDir -TargetDir $qwenTargetDir -NodeExe $nodeExe -NpmCli $npmCli | Out-Null

# Resolve the npm bin entry dynamically (0.21.x uses cli-entry.js; older used cli.js).
$qwenPackageJson = Join-Path $qwenTargetDir "node_modules\@qwen-code\qwen-code\package.json"
if (-not (Test-Path -LiteralPath $qwenPackageJson -PathType Leaf)) {
    throw "Bundled Qwen package.json is missing: $qwenPackageJson"
}
$qwenPkg = Get-Content -LiteralPath $qwenPackageJson -Raw | ConvertFrom-Json
$qwenBinRelative = $null
if ($qwenPkg.bin -is [string]) {
    $qwenBinRelative = [string]$qwenPkg.bin
} elseif ($qwenPkg.bin.qwen) {
    $qwenBinRelative = [string]$qwenPkg.bin.qwen
} else {
    throw "Bundled Qwen package.json is missing a bin.qwen entry"
}
$qwenEntry = Join-Path (Split-Path -Parent $qwenPackageJson) $qwenBinRelative
if (-not (Test-Path -LiteralPath $qwenEntry -PathType Leaf)) {
    throw "Bundled Qwen entry is missing: $qwenEntry"
}
$qwenVersionOutput = (& $nodeExe $qwenEntry --version 2>&1 | Out-String).Trim()
if ($LASTEXITCODE -ne 0) { throw "Bundled Qwen --version smoke failed (exit $LASTEXITCODE): $qwenVersionOutput" }
if ([string]::IsNullOrWhiteSpace($qwenVersionOutput)) { throw "Bundled Qwen --version smoke produced no output" }
Write-Host "    Qwen --version smoke passed: $qwenVersionOutput"

# Release/CI ACP smoke must NOT call session/new or prompt (no login / network).
$acpProbe = Join-Path $RepoRoot "tools\acp-initialize-probe.mjs"
if (-not (Test-Path -LiteralPath $acpProbe -PathType Leaf)) {
    throw "ACP initialize probe is missing: tools/acp-initialize-probe.mjs"
}
& $nodeExe $acpProbe -- $nodeExe $qwenEntry --acp | Out-Host
if ($LASTEXITCODE -ne 0) { throw "Bundled Qwen ACP initialize smoke failed (exit $LASTEXITCODE)" }
Write-Host "    Qwen ACP initialize smoke passed"
Write-Host "    Installed Qwen Code into staging/tools/qwen/"
Write-Host ""

# ---- step 6: bundle OpenCode ACP runtime ----
Write-Host "==> [6/7] Install OpenCode ACP runtime into staging/tools/opencode" -ForegroundColor Cyan
$opencodeSeedDir = Join-Path $RepoRoot "tools\opencode-seed"
$opencodeTargetDir = Join-Path $StagingDir "tools\opencode"
$opencodeResolvedVersion = Install-BundledRuntime -Label "OpenCode" -PackageName "opencode-windows-x64" -SeedDir $opencodeSeedDir -TargetDir $opencodeTargetDir -NodeExe $nodeExe -NpmCli $npmCli

# OpenCode ships as a native Bun-compiled executable inside the platform
# package. PSX depends on opencode-windows-x64 directly - never the
# opencode-ai wrapper, whose bin is a 479-byte placeholder hydrated by a
# postinstall script.
$opencodeExe = Join-Path $opencodeTargetDir "node_modules\opencode-windows-x64\bin\opencode.exe"
if (-not (Test-Path -LiteralPath $opencodeExe -PathType Leaf)) {
    throw "Bundled OpenCode executable is missing: $opencodeExe"
}

if ($SkipOpenCodeSmoke) {
    # Static fallback for build machines where security software blocks the
    # unsigned Bun binary from running: identity comes from the installed
    # package, which must match the expected version exactly.
    $opencodePackageJsonPath = Join-Path $opencodeTargetDir "node_modules\opencode-windows-x64\package.json"
    if (-not (Test-Path -LiteralPath $opencodePackageJsonPath -PathType Leaf)) {
        throw "Bundled OpenCode package.json is missing: $opencodePackageJsonPath"
    }
    $opencodeBundledVersion = (Get-Content -Raw -LiteralPath $opencodePackageJsonPath | ConvertFrom-Json).version
    if ([string]::IsNullOrWhiteSpace($opencodeBundledVersion)) { throw "Bundled OpenCode package.json carries no version" }
    # Expected version: the build-time-resolved npm `latest` in always-current
    # mode, or the committed seed manifest pin under -PinRuntimes. The pin comes
    # from the seed manifest, not the lockfile: PS 5.1 ConvertFrom-Json chokes on
    # duplicate keys that npm lockfiles legitimately contain.
    if (-not [string]::IsNullOrWhiteSpace($opencodeResolvedVersion)) {
        $opencodeExpectedVersion = $opencodeResolvedVersion
    } else {
        $opencodeSeedManifestPath = Join-Path $opencodeSeedDir "package.json"
        $opencodeExpectedVersion = (Get-Content -Raw -LiteralPath $opencodeSeedManifestPath | ConvertFrom-Json).dependencies.'opencode-windows-x64'
    }
    if ([string]::IsNullOrWhiteSpace($opencodeExpectedVersion)) { throw "Could not determine the expected OpenCode version" }
    if ($opencodeBundledVersion -ne $opencodeExpectedVersion) {
        throw "Bundled OpenCode version $opencodeBundledVersion does not match the expected version $opencodeExpectedVersion"
    }
    Write-Host "    OpenCode native smokes SKIPPED (-SkipOpenCodeSmoke); static version check passed: $opencodeBundledVersion" -ForegroundColor Yellow
    Write-Warning "OpenCode --version and ACP initialize smokes were skipped. Smoke-test the produced package on a machine where opencode.exe is allowed to run."
} else {
    try {
        $opencodeVersionOutput = (& $opencodeExe --version 2>&1 | Out-String).Trim()
        $opencodeVersionExit = $LASTEXITCODE
    } catch {
        throw "Bundled OpenCode --version smoke could not start opencode.exe: $($_.Exception.Message) If security software (Defender/EDR/360) blocks the unsigned Bun binary on this build machine, whitelist it or rerun with -SkipOpenCodeSmoke to fall back to static checks."
    }
    if ($opencodeVersionExit -ne 0) { throw "Bundled OpenCode --version smoke failed (exit $opencodeVersionExit): $opencodeVersionOutput" }
    if ([string]::IsNullOrWhiteSpace($opencodeVersionOutput)) { throw "Bundled OpenCode --version smoke produced no output" }
    Write-Host "    OpenCode --version smoke passed: $opencodeVersionOutput"

    # Release/CI ACP smoke must NOT call session/new or prompt (no login / network).
    & $nodeExe $acpProbe -- $opencodeExe acp | Out-Host
    if ($LASTEXITCODE -ne 0) { throw "Bundled OpenCode ACP initialize smoke failed (exit $LASTEXITCODE)" }
    Write-Host "    OpenCode ACP initialize smoke passed"
}
Write-Host "    Installed OpenCode into staging/tools/opencode/"
Write-Host ""

# ---- step 6: optional WebView2 Fixed Version runtime ----
$fixedWebView2Source = Resolve-WebView2FixedRuntimeDirectory $WebView2FixedRuntimePath
if ($fixedWebView2Source) {
    Write-Host "==> [7/7] Bundle WebView2 Fixed Version runtime" -ForegroundColor Cyan
    $fixedWebView2Target = Join-Path $StagingDir "runtime\webview2-fixed"
    if (Test-Path $fixedWebView2Target) {
        Remove-Item -Recurse -Force $fixedWebView2Target
    }
    New-Item -ItemType Directory -Path $fixedWebView2Target -Force | Out-Null
    Copy-Item -Recurse -Force (Join-Path $fixedWebView2Source "*") $fixedWebView2Target
    Write-Host "    Copied fixed runtime from $fixedWebView2Source"
} else {
    Write-Host "==> [7/7] WebView2 runtime is NOT bundled" -ForegroundColor Yellow
    Write-Host "    Users without WebView2 will see a prompt asking them to install it."
}
Write-Host ""

# ---- validate public package contents ----
Write-Host "==> Validate public package contents" -ForegroundColor Cyan
$requiredFiles = @(
    "PSX.exe",
    "PSX.dll",
    "e_sqlite3.dll",
    "psx.ini",
    "LICENSE.txt",
    "THIRD-PARTY-NOTICES.md",
    "licenses\acp\LICENSE",
    "licenses\kimi\LICENSE",
    "licenses\kimi\THIRD-PARTY-NOTICES.md",
    "licenses\qwen\LICENSE",
    "licenses\qwen\THIRD-PARTY-NOTICES.md",
    "licenses\opencode\LICENSE",
    "licenses\opencode\THIRD-PARTY-NOTICES.md",
    "licenses\microsoft.data.sqlite\LICENSE.txt",
    "licenses\sqlitepclraw\LICENSE",
    "licenses\sqlite\LICENSE.txt",
    "licenses\communitytoolkit.mvvm\License.md",
    "licenses\dotnet\LICENSE.txt",
    "licenses\microsoft.extensions\LICENSE.TXT",
    "licenses\webview2\LICENSE.txt",
    "licenses\react\LICENSE.txt",
    "licenses\xterm\LICENSE",
    "licenses\shadcn\LICENSE",
    "licenses\ai-elements\LICENSE",
    "licenses\streamdown\LICENSE",
    "licenses\shiki\LICENSE",
    "licenses\katex\LICENSE",
    "licenses\mermaid\LICENSE",
    "licenses\radix-ui\LICENSE",
    "licenses\lucide\LICENSE",
    "licenses\tailwindcss\LICENSE",
    "licenses\maple-mono\LICENSE.txt",
    "theme-presets\base-light.ini",
    "theme-presets\charcoal.ini",
    "theme-presets\meadow-green.ini",
    "theme-presets\parchment.ini",
    "theme-presets\vercel-black.ini",
    "wwwroot\app\index.html",
    "wwwroot\app\.vite\manifest.json",
    "wwwroot\vendor\fonts\maple-mono\MapleMonoNormal-CN-Regular.ttf",
    "wwwroot\vendor\fonts\maple-mono\MapleMonoNormal-CN-SemiBold.ttf",
    "tools\node\node.exe",
    "tools\node\LICENSE",
    "tools\node\node_modules\npm\LICENSE",
    "tools\node\node_modules\npm\bin\npm-cli.js",
    "tools\acp-seed\package.json",
    "tools\acp-seed\.npmrc",
    "tools\dsh-seed\package.json",
    "tools\dsh-seed\package-lock.json",
    "tools\dsh-seed\.npmrc",
    "tools\dsh-locks\catalog.json",
    "licenses\dsh\LICENSE",
    "licenses\dsh\THIRD-PARTY-NOTICES.md",
    "tools\kimi\package.json",
    "tools\kimi\package-lock.json",
    "tools\kimi\node_modules\@moonshot-ai\kimi-code\package.json",
    "tools\kimi\node_modules\@moonshot-ai\kimi-code\dist\main.mjs",
    "tools\qwen\package.json",
    "tools\qwen\package-lock.json",
    "tools\qwen\node_modules\@qwen-code\qwen-code\package.json",
    "tools\opencode\package.json",
    "tools\opencode\package-lock.json",
    "tools\opencode\node_modules\opencode-windows-x64\package.json",
    "tools\opencode\node_modules\opencode-windows-x64\bin\opencode.exe"
)
# Keep the resolved Qwen bin entry in the required set (dynamic; not hardcoded
# to cli-entry.js so a future bin rename still validates).
$qwenEntryRelative = $qwenEntry.Substring($StagingDir.Length).TrimStart('\').Replace('/', '\')
$requiredFiles += $qwenEntryRelative
foreach ($relativePath in $requiredFiles) {
    $fullPath = Join-Path $StagingDir $relativePath
    if (-not (Test-Path -LiteralPath $fullPath -PathType Leaf)) {
        throw "Required release file is missing: $relativePath"
    }
}

$mapleMonoFiles = @{
    "wwwroot\vendor\fonts\maple-mono\MapleMonoNormal-CN-Regular.ttf" = $MapleMonoRegularExpectedSha
    "wwwroot\vendor\fonts\maple-mono\MapleMonoNormal-CN-SemiBold.ttf" = $MapleMonoSemiBoldExpectedSha
}
foreach ($entry in $mapleMonoFiles.GetEnumerator()) {
    $actualHash = (Get-FileHash -LiteralPath (Join-Path $StagingDir $entry.Key) -Algorithm SHA256).Hash
    if (-not [string]::Equals($actualHash, $entry.Value, [StringComparison]::OrdinalIgnoreCase)) {
        throw "Bundled Maple Mono font hash mismatch: $($entry.Key)"
    }
}

$dshSeedRoot = Join-Path $StagingDir "tools\dsh-seed"
$dshLockPath = Join-Path $dshSeedRoot "package-lock.json"
$dshLockHash = (Get-FileHash -LiteralPath $dshLockPath -Algorithm SHA256).Hash
if (-not [string]::Equals($dshLockHash, $DshSeedLockExpectedSha, [StringComparison]::OrdinalIgnoreCase)) {
    throw "DSH seed lockfile hash mismatch. Review and update the pinned supply-chain evidence explicitly."
}
$dshManifest = Get-Content -Raw -LiteralPath (Join-Path $dshSeedRoot "package.json") | ConvertFrom-Json
if ($dshManifest.dependencies.'@deepseek-ai/dsh' -ne $DshPinnedVersion) {
    throw "DSH seed must pin @deepseek-ai/dsh to $DshPinnedVersion."
}
$dshLockText = Get-Content -Raw -LiteralPath $dshLockPath
if ($dshLockText -match '"resolved"\s*:\s*"https://(?!registry\.npmjs\.org/)') {
    throw "DSH seed lockfile contains a non-official npm registry resolved URL."
}
# PS 5.1 ConvertFrom-Json rejects npm lockfiles that use an empty "" packages
# key. Read the pinned entry from text instead of parsing the whole file.
$dshLockMatch = [regex]::Match(
    $dshLockText,
    '"node_modules/@deepseek-ai/dsh"\s*:\s*\{\s*"version"\s*:\s*"(?<version>[^"]+)"[\s\S]*?"integrity"\s*:\s*"(?<integrity>[^"]+)"')
if (-not $dshLockMatch.Success `
    -or $dshLockMatch.Groups['version'].Value -ne $DshPinnedVersion `
    -or [string]::IsNullOrWhiteSpace($dshLockMatch.Groups['integrity'].Value)) {
    throw "DSH lockfile @deepseek-ai/dsh version or integrity evidence is incomplete."
}
$dshNpmrcText = Get-Content -Raw -LiteralPath (Join-Path $dshSeedRoot ".npmrc")
if ($dshNpmrcText -notmatch 'registry=https://registry\.npmjs\.org/') {
    throw "DSH seed .npmrc must pin the official npm registry."
}

# ---- DSH update-lock catalog: static verification only. The release/signing
# machine never executes package code; generation, official-integrity checks
# and the launch smoke happen exclusively in the generator's disposable
# environment (see tools/generate-dsh-lock.ps1). ----
$dshLocksRoot = Join-Path $StagingDir "tools\dsh-locks"
$dshCatalogPath = Join-Path $dshLocksRoot "catalog.json"
$dshCatalogHash = (Get-FileHash -LiteralPath $dshCatalogPath -Algorithm SHA256).Hash
if (-not [string]::Equals($dshCatalogHash, $DshLockCatalogExpectedSha, [StringComparison]::OrdinalIgnoreCase)) {
    throw "DSH lock catalog hash mismatch. Expected $DshLockCatalogExpectedSha but got $dshCatalogHash. Review the catalog diff and update the pinned evidence explicitly."
}
$dshCatalog = Get-Content -Raw -LiteralPath $dshCatalogPath | ConvertFrom-Json
if ([int]$dshCatalog.schemaVersion -ne 1) {
    throw "DSH lock catalog schemaVersion must be 1."
}
$dshCatalogEntries = @($dshCatalog.entries)
$dshBlockedEntries = @($dshCatalog.blockedVersions)
if ($dshCatalogEntries.Count -gt 5) {
    Write-Warning "DSH lock catalog carries $($dshCatalogEntries.Count) entries; policy keeps at most five."
}
if ($dshBlockedEntries.Count -gt 10) {
    throw "DSH lock catalog blockedVersions exceeds ten entries."
}
$dshEntryVersions = @($dshCatalogEntries | ForEach-Object { [string]$_.version })
$dshBlockedVersions = @($dshBlockedEntries | ForEach-Object { [string]$_.version })
foreach ($blockedEntry in $dshBlockedEntries) {
    if ($DshLockBlockedReasons -notcontains [string]$blockedEntry.reason) {
        throw "DSH blocked entry $($blockedEntry.version) has a non-fixed reason '$($blockedEntry.reason)'."
    }
    if ($dshEntryVersions -contains [string]$blockedEntry.version) {
        throw "DSH version $($blockedEntry.version) is both bundled and blocked."
    }
}
foreach ($entry in $dshCatalogEntries) {
    $entryVersion = [string]$entry.version
    $entryRoot = Join-Path $dshLocksRoot ("locks\" + $entryVersion)
    $entryLockPath = Join-Path $entryRoot "package-lock.json"
    $entryPackagePath = Join-Path $entryRoot "package.json"
    foreach ($entryFile in @($entryLockPath, $entryPackagePath)) {
        if (-not (Test-Path -LiteralPath $entryFile -PathType Leaf)) {
            throw "DSH lock catalog entry $entryVersion is missing: $entryFile"
        }
    }
    if (-not [string]::Equals((Get-FileHash -LiteralPath $entryLockPath -Algorithm SHA256).Hash, [string]$entry.lockSha256, [StringComparison]::OrdinalIgnoreCase)) {
        throw "DSH lock catalog entry $entryVersion lockfile hash mismatch."
    }
    if (-not [string]::Equals((Get-FileHash -LiteralPath $entryPackagePath -Algorithm SHA256).Hash, [string]$entry.packageSha256, [StringComparison]::OrdinalIgnoreCase)) {
        throw "DSH lock catalog entry $entryVersion package.json hash mismatch."
    }
    $entryLockText = Get-Content -Raw -LiteralPath $entryLockPath
    if ($entryLockText -notmatch '"lockfileVersion"\s*:\s*3') {
        throw "DSH lock catalog entry $entryVersion is not lockfileVersion 3."
    }
    if ($entryLockText -match '"resolved"\s*:\s*"https://(?!registry\.npmjs\.org/)') {
        throw "DSH lock catalog entry $entryVersion contains a non-official registry resolved URL."
    }
    if ($entryLockText -notmatch ('"@deepseek-ai/dsh"\s*:\s*"{0}"' -f [regex]::Escape($entryVersion))) {
        throw "DSH lock catalog entry $entryVersion root dependency is not pinned exactly."
    }
    $entrySriMatch = [regex]::Match(
        $entryLockText,
        '"node_modules/@deepseek-ai/dsh"\s*:\s*\{\s*"version"\s*:\s*"(?<version>[^"]+)"[\s\S]*?"integrity"\s*:\s*"(?<integrity>[^"]+)"')
    if (-not $entrySriMatch.Success -or $entrySriMatch.Groups['version'].Value -ne $entryVersion) {
        throw "DSH lock catalog entry $entryVersion has no integrity-pinned DSH entry."
    }
    if (-not [string]::Equals($entrySriMatch.Groups['integrity'].Value, [string]$entry.dshSri, [StringComparison]::Ordinal)) {
        throw "DSH lock catalog entry $entryVersion dshSri does not equal the lockfile DSH entry SRI."
    }
    if (-not [bool]$entry.smokePassed) {
        throw "DSH lock catalog entry $entryVersion has not passed the launch smoke."
    }
    # Include per-version files in the required set so the zip double-check
    # below verifies them too (the file list itself is dynamic).
    $requiredFiles += @(
        "tools\dsh-locks\locks\$entryVersion\package.json",
        "tools\dsh-locks\locks\$entryVersion\package-lock.json"
    )
}
$dshLocksVersionsRoot = Join-Path $dshLocksRoot "locks"
if (Test-Path -LiteralPath $dshLocksVersionsRoot) {
    $onDiskVersions = @(Get-ChildItem -LiteralPath $dshLocksVersionsRoot -Directory | ForEach-Object { $_.Name })
    foreach ($orphan in @($onDiskVersions | Where-Object { $dshEntryVersions -notcontains $_ })) {
        throw "DSH locks directory '$orphan' is not listed in the catalog."
    }
}
Write-Host "    DSH lock catalog verified: $($dshCatalogEntries.Count) entr(ies), $($dshBlockedEntries.Count) blocked."
Assert-DshSeedConsistency -SeedRoot $dshSeedRoot -LocksRoot $dshLocksRoot `
    -Entries $dshCatalogEntries -PinnedVersion $DshPinnedVersion `
    -RuntimeSource ([IO.File]::ReadAllText((Join-Path $RepoRoot 'Services\DshWebRuntime.cs')))

# ---- DSH catalog freshness gate (metadata-only query; never executes
# package code). The newest published version above the seed must be covered
# by entries ∪ blockedVersions only when explicitly requested. Registry
# unreachability is fatal in that opt-in audit, never in default packaging. ----
if ($RequireLatestDsh) {
    Write-Host "    DSH opt-in catalog coverage audit (does not require latest seed)."
    $dshSemverTool = Join-Path $RepoRoot "tools\dsh-semver.mjs"
    $dshViewJson = & $nodeExe $npmCli view "@deepseek-ai/dsh" versions --json --registry=https://registry.npmjs.org/
    if ($LASTEXITCODE -ne 0) {
        throw "DSH freshness gate failed: could not query the official npm registry (npm view exit $LASTEXITCODE)."
    }
    $dshPublishedVersions = @((ConvertFrom-Json ($dshViewJson -join "`n")) | ForEach-Object { [string]$_ })
    $dshNewest = "$(& $nodeExe $dshSemverTool "latest" $DshPinnedVersion @dshPublishedVersions)".Trim()
    if ($LASTEXITCODE -ne 0) {
        throw "DSH freshness gate failed: dsh-semver.mjs could not rank the published versions."
    }
    if (-not [string]::IsNullOrWhiteSpace($dshNewest)) {
        if ($dshEntryVersions -notcontains $dshNewest -and $dshBlockedVersions -notcontains $dshNewest) {
            throw @"
DSH freshness gate failed: @deepseek-ai/dsh@$dshNewest is published above the
seed but is neither bundled nor blocked in tools/dsh-locks/catalog.json. Run
tools/generate-dsh-lock.ps1 -Version $dshNewest in its disposable environment
(generation + official integrity check + launch smoke), or add a reviewed
blockedVersions entry, then update `$DshLockCatalogExpectedSha.
"@
        }
        Write-Host "    DSH freshness gate passed: newest published $dshNewest is covered by the catalog."
    } else {
        Write-Host "    DSH freshness gate passed: no published version is newer than the seed."
    }
}

$forbiddenAcpRuntime = Join-Path $StagingDir "runtime\acp-current"
if (Test-Path -LiteralPath $forbiddenAcpRuntime) {
    throw "Public release must not contain runtime/acp-current."
}

$forbiddenOpencodeRuntime = Join-Path $StagingDir "runtime\opencode-current"
if (Test-Path -LiteralPath $forbiddenOpencodeRuntime) {
    throw "Public release must not contain runtime/opencode-current."
}

foreach ($forbiddenDshName in @("dsh-current", "dsh-next", "dsh-installing", "dsh-rollback")) {
    $forbiddenDshRuntime = Join-Path $StagingDir "runtime\$forbiddenDshName"
    if (Test-Path -LiteralPath $forbiddenDshRuntime) {
        throw "Public release must not contain runtime/$forbiddenDshName."
    }
}

$forbiddenFiles = @(Get-ChildItem -LiteralPath $StagingDir -Recurse -File | Where-Object {
    $relative = $_.FullName.Substring($StagingDir.Length).TrimStart('\').Replace('\', '/')
    $strayNodeModules = ($relative -match '(^|/)node_modules/') -and (-not $relative.StartsWith('tools/node/node_modules/', [StringComparison]::OrdinalIgnoreCase)) -and (-not $relative.StartsWith('tools/kimi/node_modules/', [StringComparison]::OrdinalIgnoreCase)) -and (-not $relative.StartsWith('tools/qwen/node_modules/', [StringComparison]::OrdinalIgnoreCase)) -and (-not $relative.StartsWith('tools/opencode/node_modules/', [StringComparison]::OrdinalIgnoreCase))
    # Source maps and TypeScript are forbidden only for the generated Vite
    # output (vendored passthrough files under wwwroot/app/vendor may ship
    # upstream maps). Portable Node/npm legitimately contains maps.
    $agentSourceArtifact = $relative.StartsWith('wwwroot/app/', [StringComparison]::OrdinalIgnoreCase) -and (-not $relative.StartsWith('wwwroot/app/vendor/', [StringComparison]::OrdinalIgnoreCase)) -and $_.Extension -in @('.ts', '.map')
    $_.Name -ieq "claude.exe" `
        -or $_.Extension -in @(".log", ".tmp", ".binlog") `
        -or $agentSourceArtifact `
        -or $relative.StartsWith('frontend/', [StringComparison]::OrdinalIgnoreCase) `
        -or $strayNodeModules `
        -or $relative.StartsWith('tests/', [StringComparison]::OrdinalIgnoreCase) `
        -or $relative.StartsWith('TestResults/', [StringComparison]::OrdinalIgnoreCase) `
        -or $_.Name -like 'PSX.Tests.*' `
        -or $_.Name -like 'PSX.TestAgent.*' `
        -or $_.Name -like 'PSX.TestNpm.*' `
        -or $_.Name -like 'PSX.DesktopProbe.*'
})
if ($forbiddenFiles.Count -gt 0) {
    $paths = ($forbiddenFiles | ForEach-Object { $_.FullName.Substring($StagingDir.Length).TrimStart('\') }) -join ", "
    throw "Public release contains forbidden files: $paths"
}
Write-Host "    Required files present; no Claude binary, installed ACP runtime, logs, or temp files found."
Write-Host ""

# ---- produce zip ----
Write-Host "==> Packaging zip" -ForegroundColor Cyan
New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null

# Read version from PSX.csproj
$csproj = Get-Content $ProjectPath -Raw
$versionMatch = [regex]::Match($csproj, '<Version>([^<]+)</Version>')
if (-not $versionMatch.Success) {
    throw "Project version is missing from $ProjectPath. Add a <Version> element before building a release."
}
$version = $versionMatch.Groups[1].Value.Trim()

$zipPath = Join-Path $OutputDirectory "PSX-$version-win-x64-portable.zip"
if (Test-Path $zipPath) { Remove-Item $zipPath -Force }

# Use .NET Compression for cross-platform zips; for Windows-only zips we
# could use Compress-Archive but that often produces non-standard headers.
Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem
[System.IO.Compression.ZipFile]::CreateFromDirectory(
    $StagingDir,
    $zipPath,
    [System.IO.Compression.CompressionLevel]::Optimal,
    $false  # includeBaseDirectory: false — zip root should be PSX.exe directly
)

$archive = [System.IO.Compression.ZipFile]::OpenRead($zipPath)
try {
    $entryNames = @($archive.Entries | ForEach-Object { $_.FullName.Replace('\', '/') })
    foreach ($requiredFile in $requiredFiles) {
        $requiredEntry = $requiredFile.Replace('\', '/')
        if ($entryNames -notcontains $requiredEntry) {
            throw "Required file is missing from the completed zip: $requiredEntry"
        }
    }

    $forbiddenEntries = @($entryNames | Where-Object {
        $normalized = $_.Replace('\', '/')
        $leaf = [IO.Path]::GetFileName($normalized)
        $extension = [IO.Path]::GetExtension($normalized)
        $strayNodeModules = ($normalized -match '(^|/)node_modules/') -and (-not $normalized.StartsWith('tools/node/node_modules/', [StringComparison]::OrdinalIgnoreCase)) -and (-not $normalized.StartsWith('tools/kimi/node_modules/', [StringComparison]::OrdinalIgnoreCase)) -and (-not $normalized.StartsWith('tools/qwen/node_modules/', [StringComparison]::OrdinalIgnoreCase)) -and (-not $normalized.StartsWith('tools/opencode/node_modules/', [StringComparison]::OrdinalIgnoreCase))
        # Keep this scoped to the Vite output for parity with the staging
        # check; Node/npm and wwwroot/app/vendor files can ship source maps.
        $agentSourceArtifact = $normalized.StartsWith('wwwroot/app/', [StringComparison]::OrdinalIgnoreCase) -and (-not $normalized.StartsWith('wwwroot/app/vendor/', [StringComparison]::OrdinalIgnoreCase)) -and $extension -in @('.ts', '.map')
        $normalized.StartsWith('runtime/acp-current/', [StringComparison]::OrdinalIgnoreCase) `
            -or $normalized.StartsWith('runtime/opencode-current/', [StringComparison]::OrdinalIgnoreCase) `
            -or $normalized.StartsWith('tests/', [StringComparison]::OrdinalIgnoreCase) `
            -or $normalized.StartsWith('TestResults/', [StringComparison]::OrdinalIgnoreCase) `
            -or $normalized.StartsWith('frontend/', [StringComparison]::OrdinalIgnoreCase) `
            -or $agentSourceArtifact `
            -or $strayNodeModules `
            -or $leaf -ieq 'claude.exe' `
            -or $leaf -like 'PSX.Tests.*' `
            -or $leaf -like 'PSX.TestAgent.*' `
            -or $leaf -like 'PSX.TestNpm.*' `
            -or $leaf -like 'PSX.DesktopProbe.*' `
            -or $extension -in @('.log', '.tmp', '.binlog')
    })
    if ($forbiddenEntries.Count -gt 0) {
        throw "Completed zip contains forbidden entries: $($forbiddenEntries -join ', ')"
    }
}
finally {
    $archive.Dispose()
}

$zipSize = [math]::Round((Get-Item $zipPath).Length / 1MB, 1)
$zipSha256 = (Get-FileHash -LiteralPath $zipPath -Algorithm SHA256).Hash.ToLowerInvariant()
Write-Host "    Wrote $zipPath ($zipSize MB)"
Write-Host "    SHA-256: $zipSha256"
Write-Host "    Verified completed zip contents."
Write-Host ""
Write-Host "==> Done." -ForegroundColor Green
