// vendor-react.mjs — reproducibly regenerate wwwroot/vendor/react/ from the
// exact React version pinned in the root package.json. Run only when React is
// upgraded: `npm run vendor:react`. Application builds (build:agent, Fast
// Suite, dotnet build) never run this bundler; the committed output is the
// single source of truth, described by vendor-manifest.json.
//
// Shape: one self-contained core bundle + generated facades. React ships CJS,
// and esbuild's CJS->ESM output exposes only a default export while external
// require() calls become runtime "Dynamic require" throws, so per-entry
// bundles with externals cannot provide `import { useState } from "react"`.
// Bundling all four entries into a single react-core.js guarantees one React
// instance structurally, and each bare specifier gets a facade whose named
// exports are enumerated from the real module at vendor time.

import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import fs from 'node:fs';

const require = createRequire(import.meta.url);
const esbuild = require('esbuild');

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '..');
const outDir = path.join(repoRoot, 'wwwroot', 'vendor', 'react');

const reactVersion = require('react/package.json').version;
const reactDomVersion = require('react-dom/package.json').version;
const esbuildVersion = require('esbuild/package.json').version;

if (reactVersion !== reactDomVersion) {
  console.error(`[vendor:react] react ${reactVersion} != react-dom ${reactDomVersion}; align the pinned versions first.`);
  process.exit(1);
}

// namespace export name in react-core.js -> bare specifier + facade file.
const entries = [
  { ns: 'React', specifier: 'react', outFile: 'react.js' },
  { ns: 'ReactJsxRuntime', specifier: 'react/jsx-runtime', outFile: 'react-jsx-runtime.js' },
  { ns: 'ReactDom', specifier: 'react-dom', outFile: 'react-dom.js' },
  { ns: 'ReactDomClient', specifier: 'react-dom/client', outFile: 'react-dom-client.js' }
];

fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

// 1) Single self-contained core bundle: every entry lives in one module graph,
// so the page can only ever contain one React instance.
const coreSource = entries
  .map(({ ns, specifier }) => `import * as ${ns} from ${JSON.stringify(specifier)};`)
  .concat([`export { ${entries.map((e) => e.ns).join(', ')} };`])
  .join('\n');

await esbuild.build({
  stdin: { contents: coreSource, resolveDir: repoRoot, sourcefile: 'react-core-entry.js', loader: 'js' },
  outfile: path.join(outDir, 'react-core.js'),
  bundle: true,
  platform: 'browser',
  format: 'esm',
  target: 'es2022',
  minify: true,
  sourcemap: false,
  legalComments: 'none',
  define: { 'process.env.NODE_ENV': '"production"' },
  conditions: ['browser', 'production'],
  logLevel: 'error'
});

// 2) Facades: enumerate the real export names at vendor time and re-export
// them from the core namespace, so `import { useState } from "react"` works
// through the import map.
const identifier = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
for (const { ns, specifier, outFile } of entries) {
  const names = Object.keys(require(specifier))
    .filter((name) => name !== 'default' && name !== '__esModule' && identifier.test(name))
    .sort();
  const lines = [
    `// Generated by \`npm run vendor:react\` for ${specifier}@${reactVersion}; do not edit.`,
    `import { ${ns} } from './react-core.js';`,
    `export const { ${names.join(', ')} } = ${ns};`,
    `export default ${ns}.default;`,
    ''
  ];
  fs.writeFileSync(path.join(outDir, outFile), lines.join('\n'));
}

// 3) Manifest with hashes + the allowed import surface per file, consumed by
// the static guard test.
const manifestFiles = ['react-core.js', ...entries.map((e) => e.outFile)].map((file) => {
  const contents = fs.readFileSync(path.join(outDir, file));
  return {
    file,
    imports: file === 'react-core.js' ? [] : ['./react-core.js'],
    bytes: contents.length,
    sha256: createHash('sha256').update(contents).digest('hex')
  };
});

const manifest = {
  reactVersion,
  esbuildVersion,
  command: 'npm run vendor:react',
  generated: new Date().toISOString().slice(0, 10),
  files: manifestFiles
};
fs.writeFileSync(path.join(outDir, 'vendor-manifest.json'), JSON.stringify(manifest, null, 2) + '\n');

fs.writeFileSync(
  path.join(outDir, 'README.txt'),
  [
    'Offline React ESM bundles for the Agent frontend import map.',
    '',
    `React version:   ${reactVersion}`,
    `esbuild version: ${esbuildVersion}`,
    'Regenerate with: npm run vendor:react (only when upgrading React).',
    '',
    'react-core.js bundles react, react/jsx-runtime, react-dom and',
    'react-dom/client into one self-contained module graph (single React',
    'instance by construction). The other files are generated facades that',
    're-export named bindings for the import map bare specifiers.',
    '',
    'File hashes and the allowed import surface live in vendor-manifest.json;',
    'the static guard test in tests/PSX.Web.Tests verifies both, so never',
    'edit these files by hand.',
    ''
  ].join('\n')
);

for (const f of manifestFiles) console.log(`[vendor:react] ${f.file} (${f.bytes} bytes)`);
console.log(`[vendor:react] wrote ${manifestFiles.length} files + manifest to ${outDir}`);
